services:

  postgres:
    image: postgres:16
    container_name: football_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      default:
        aliases:
          - football-postgres

  dbmate:
    image: ghcr.io/amacneil/dbmate:2
    container_name: football_dbmate
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable
      DBMATE_MIGRATIONS_DIR: /db/migrations
    volumes:
      - ./db/migrations:/db/migrations
    command: --wait --migrations-dir /db/migrations up
    restart: "no"

  minio:
    image: minio/minio:latest
    container_name: football_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  airflow-init:
    build:
      context: .
      dockerfile: infra/airflow/Dockerfile
    image: football-airflow:local
    container_name: football_airflow_init
    depends_on:
      postgres:
        condition: service_started
      dbmate:
        condition: service_completed_successfully
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ${AIRFLOW__DATABASE__SQL_ALCHEMY_CONN}
      AIRFLOW__CORE__FERNET_KEY: ""
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW__WEBSERVER__SECRET_KEY}
      AIRFLOW__CORE__ENABLE_XCOM_PICKLING: "true"
      APIFOOTBALL_API_KEY: ${APIFOOTBALL_API_KEY}
      APIFOOTBALL_BASE_URL: ${APIFOOTBALL_BASE_URL}
      MINIO_ENDPOINT_URL: ${MINIO_ENDPOINT_URL}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      FOOTBALL_PG_DSN: ${FOOTBALL_PG_DSN}



    command: >
      bash -lc "airflow db init &&
      airflow users create --username admin --password admin --firstname admin --lastname user --role Admin --email admin@example.com"

  airflow-webserver:
    image: football-airflow:local
    container_name: football_airflow_webserver
    depends_on:
      - airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ${AIRFLOW__DATABASE__SQL_ALCHEMY_CONN}
      AIRFLOW__CORE__FERNET_KEY: ""
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW__WEBSERVER__SECRET_KEY}
      AIRFLOW__CORE__ENABLE_XCOM_PICKLING: "true"
      APIFOOTBALL_API_KEY: ${APIFOOTBALL_API_KEY}
      APIFOOTBALL_BASE_URL: ${APIFOOTBALL_BASE_URL}
      MINIO_ENDPOINT_URL: ${MINIO_ENDPOINT_URL}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      FOOTBALL_PG_DSN: ${FOOTBALL_PG_DSN}



    volumes:
      - ./infra/airflow/dags:/opt/airflow/dags
      - ./warehouse:/opt/airflow/warehouse
      - ./dbt:/opt/airflow/dbt
      - ./quality:/opt/airflow/quality
    ports:
      - "8080:8080"
    command: webserver

  airflow-scheduler:
    image: football-airflow:local
    container_name: football_airflow_scheduler
    depends_on:
      - airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ${AIRFLOW__DATABASE__SQL_ALCHEMY_CONN}
      AIRFLOW__CORE__FERNET_KEY: ""
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW__WEBSERVER__SECRET_KEY}
      AIRFLOW__CORE__ENABLE_XCOM_PICKLING: "true"
      APIFOOTBALL_API_KEY: ${APIFOOTBALL_API_KEY}
      APIFOOTBALL_BASE_URL: ${APIFOOTBALL_BASE_URL}
      MINIO_ENDPOINT_URL: ${MINIO_ENDPOINT_URL}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      FOOTBALL_PG_DSN: ${FOOTBALL_PG_DSN}



    volumes:
      - ./infra/airflow/dags:/opt/airflow/dags
      - ./warehouse:/opt/airflow/warehouse
      - ./dbt:/opt/airflow/dbt
      - ./quality:/opt/airflow/quality
    command: scheduler


  minio-init:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set local ${MINIO_ENDPOINT_URL} ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY};
      mc mb local/football-bronze;
      mc mb local/football-silver;
      mc mb local/football-gold;
      exit 0;
      "

  metabase:
    image: metabase/metabase:latest
    container_name: football_metabase
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - metabase_data:/metabase.db
    environment:
      MB_DB_FILE: /metabase.db/metabase


volumes:
  postgres_data:
  minio_data:
  metabase_data:

networks:
  default:
    name: football-network
