version: "3.9"

services:

  postgres:
    image: postgres:16
    container_name: football_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: football_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  airflow-init:
    image: apache/airflow:2.9.3
    container_name: football_airflow_init
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ${AIRFLOW__DATABASE__SQL_ALCHEMY_CONN}
      AIRFLOW__CORE__FERNET_KEY: ""
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW__WEBSERVER__SECRET_KEY}
      AIRFLOW__CORE__ENABLE_XCOM_PICKLING: "true"
      PIP_ADDITIONAL_REQUIREMENTS: "boto3 requests pandas pyarrow psycopg2-binary sqlalchemy"
      APIFOOTBALL_API_KEY: ${APIFOOTBALL_API_KEY}
      APIFOOTBALL_BASE_URL: ${APIFOOTBALL_BASE_URL}
      MINIO_ENDPOINT_URL: ${MINIO_ENDPOINT_URL}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      FOOTBALL_PG_DSN: ${FOOTBALL_PG_DSN}



    command: >
      bash -lc "airflow db init &&
      airflow users create --username admin --password admin --firstname admin --lastname user --role Admin --email admin@example.com"

  airflow-webserver:
    image: apache/airflow:2.9.3
    container_name: football_airflow_webserver
    depends_on:
      - airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ${AIRFLOW__DATABASE__SQL_ALCHEMY_CONN}
      AIRFLOW__CORE__FERNET_KEY: ""
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW__WEBSERVER__SECRET_KEY}
      AIRFLOW__CORE__ENABLE_XCOM_PICKLING: "true"
      PIP_ADDITIONAL_REQUIREMENTS: "boto3 requests pandas pyarrow psycopg2-binary sqlalchemy"
      APIFOOTBALL_API_KEY: ${APIFOOTBALL_API_KEY}
      APIFOOTBALL_BASE_URL: ${APIFOOTBALL_BASE_URL}
      MINIO_ENDPOINT_URL: ${MINIO_ENDPOINT_URL}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      FOOTBALL_PG_DSN: ${FOOTBALL_PG_DSN}



    volumes:
      - ./infra/airflow/dags:/opt/airflow/dags
    ports:
      - "8080:8080"
    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.9.3
    container_name: football_airflow_scheduler
    depends_on:
      - airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ${AIRFLOW__DATABASE__SQL_ALCHEMY_CONN}
      AIRFLOW__CORE__FERNET_KEY: ""
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW__WEBSERVER__SECRET_KEY}
      AIRFLOW__CORE__ENABLE_XCOM_PICKLING: "true"
      PIP_ADDITIONAL_REQUIREMENTS: "boto3 requests pandas pyarrow psycopg2-binary sqlalchemy"
      APIFOOTBALL_API_KEY: ${APIFOOTBALL_API_KEY}
      APIFOOTBALL_BASE_URL: ${APIFOOTBALL_BASE_URL}
      MINIO_ENDPOINT_URL: ${MINIO_ENDPOINT_URL}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      FOOTBALL_PG_DSN: ${FOOTBALL_PG_DSN}



    volumes:
      - ./infra/airflow/dags:/opt/airflow/dags
    command: scheduler


  minio-init:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set local ${MINIO_ENDPOINT_URL} ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY};
      mc mb local/football-bronze;
      mc mb local/football-silver;
      mc mb local/football-gold;
      exit 0;
      "


volumes:
  postgres_data:
  minio_data:
